//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMEntities : DbContext
    {
        public CRMEntities()
            : base("name=CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADM_CLIENT> ADM_CLIENT { get; set; }
        public virtual DbSet<ADM_DEF_ACC_MGR> ADM_DEF_ACC_MGR { get; set; }
        public virtual DbSet<ADM_DEF_BRANCH> ADM_DEF_BRANCH { get; set; }
        public virtual DbSet<ADM_DEF_BUS_TYPE> ADM_DEF_BUS_TYPE { get; set; }
        public virtual DbSet<ADM_DEF_CLIENT_TYPE> ADM_DEF_CLIENT_TYPE { get; set; }
    }
}
